### ISSUE TITLE
App

### ISSUE THREAD

**Issue by BIGEAZY289** [Kaede-No-Ki/moviecorner-app#17]
Where I can find this app of yours?

**Comment by febryardiansyah** [comment]
Hi @BIGEAZY289 !! Thanks for opening an issue, this app is currently not finished yet. You can see our progress [Here](https://github.com/Kaede-No-Ki/moviecorner-app/projects/1). We would release as soon as possible 😀

**Comment by BIGEAZY289** [comment]
Yay can I see screenshots or something

**Comment by BIGEAZY289** [comment]
Awesome can't wait anymore

**Comment by BIGEAZY289** [comment]
Is this app to be available in Indonesian language?

**Comment by febryardiansyah** [comment]
@BIGEAZY289 Yes, this app will be available for indonesian language for now. but, we would add english source in the future
